// document.writeln("<div style=\'text-align:center;overflow: hidden;\'>");
// document.writeln("<ins class=\'adsbygoogle\'");
// document.writeln("     style=\'display:inline-block;width:728px;height:90px\'");
// document.writeln("     data-ad-client=\'ca-pub-2222513431618339\'");
// document.writeln("     data-ad-slot=\'8930471380\'></ins>");
// document.writeln("</div>");

// document.writeln("<script>");
// document.writeln("(adsbygoogle = window.adsbygoogle || []).push({});");
// document.writeln("</script>");



document.writeln("<style>");
document.writeln("    #customad {");
document.writeln("        background-color: #fff;");
document.writeln("    }");
document.writeln("");
document.writeln("    #customad h1 {");
document.writeln("        color: #fff;");
document.writeln("        text-align: center;");
document.writeln("        background: #673AB7;");
document.writeln("        font-size: 60px;");
document.writeln("    }");
document.writeln("");
document.writeln("    #customad .custombd {");
document.writeln("        padding: 12px 30px;");
document.writeln("        line-height: 32px;");
document.writeln("    }");
document.writeln("");
document.writeln("    #customad .custombd .listad {");
document.writeln("        width: 50%;");
document.writeln("        text-align: center;");
document.writeln("        float: left;");
document.writeln("        color: #9C27B0;");
document.writeln("        text-decoration: underline;");
document.writeln("        font-weight: bold;");
document.writeln("    }");
document.writeln("");
document.writeln("    @media (max-width: 768px) {");
document.writeln("        #customad h1 {");
document.writeln("            font-size: 28px;");
document.writeln("        }");
document.writeln("");
document.writeln("        #customad .custombd .listad {");
document.writeln("            font-size: 14px;");
document.writeln("            width: 100% !important;");
document.writeln("            line-height: 28px;");
document.writeln("        }");
document.writeln("    }");
document.writeln("</style>");
document.writeln("<div id=\'customad\'>");
document.writeln("    <div>");
document.writeln("        <h1><a href=\'https://www.aliyun.com/minisite/goods?userCode=a9la9jwc&share_source=copy_link\'");
document.writeln("                target=\'_blank\'>推广：阿里云服务器 / 双11狂欢</a></h1>");
document.writeln("    </div>");
document.writeln("    <div class=\'custombd clearfix\'>");
document.writeln("        <a href=\'https://www.aliyun.com/1111/home?userCode=a9la9jwc\' class=\'listad\'");
document.writeln("            target=\'_blank\'>上亿元津贴限时发放，更有全年超底价上云必备限时抢购</a>");
document.writeln("        <a href=\'https://www.aliyun.com/1111/new?userCode=a9la9jwc\' class=\'listad\'");
document.writeln("            target=\'_blank\'>云服务器双11狂欢特惠，最低仅需84.97元/年，助力轻松上云</a>");
document.writeln("");
document.writeln("        <a href=\'https://promotion.aliyun.com/ntms/yunparter/invite.html?userCode=a9la9jwc\' class=\'listad\'");
document.writeln("            target=\'_blank\'>上云优惠聚集地，云小站专属代金券可叠加产品折扣使用</a>");
document.writeln("        <a href=\'https://www.aliyun.com/activity?userCode=a9la9jwc\' class=\'listad\' target=\'_blank\'>上新必买抢先知，劲爆优惠不错过！</a>");
document.writeln("");
document.writeln("        <a href=\'https://www.aliyun.com/activity/daily/bestoffer?userCode=a9la9jwc\' class=\'listad\'");
document.writeln("            target=\'_blank\'>精选全网爆款产品，爆品销量榜单，企业应用最低只要9.9，还有更多云产</a>");
document.writeln("        <a href=\'https://www.aliyun.com/daily-act/ecs/care?userCode=a9la9jwc\' class=\'listad\'");
document.writeln("            target=\'_blank\'>更高配置更强性能，阿里云助您升级。ECS实例规格变配/升级、带宽升级</a>");
document.writeln("    </div>");
document.writeln("</div>");